on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0' # The .NET SDK version to use

jobs:
  Test_Day_1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: ./Day01
      run: dotnet restore
      
    - name: Build
      working-directory: ./Day01
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      working-directory: ./Day01
      run: dotnet test --no-restore --verbosity q

  Test_Day_2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: ./Day02
      run: dotnet restore
      
    - name: Build
      working-directory: ./Day02
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      working-directory: ./Day02
      run: dotnet test --no-restore --verbosity q
  
  Test_Day_3:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: ./Day03
      run: dotnet restore
      
    - name: Build
      working-directory: ./Day03
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      working-directory: ./Day03
      run: dotnet test --no-restore --verbosity q